### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by lotur** [UDST/synthpop#36]
Hi there,
I'm trying to run synthpop but I run into an **HTTP Error 403: Forbidden**.
My census key is fine. 
The Census class defined in **census_helpers.py** sets the following URL as the base_url:

````
class Census:

    def __init__(self, key):
        self.c = census.Census(key)
        self.base_url = "https://s3-us-west-2.amazonaws.com/synthpop-data/"
````

I've tried to access it on a browser, all it says is:
**All Access Disabled All access to this object has been disabled**

I guess the problem lies there: could you please give me some pointers on how I can solve this issue?
Thank you very much!

**Comment by janowicz** [comment]
Thanks for reporting the issue @lotur.  This relates to a change in where we're hosting PUMS files.  The previous location is no longer valid, and we need to update the `base_url`.  Will keep you posted.
