### ISSUE TITLE
Mismatch between constraints and number of households to draw

### ISSUE THREAD

**Issue by frproulx** [UDST/synthpop#72]
I am running into the RunTimeError indicated here: https://github.com/UDST/synthpop/blob/274df40203c129f92d9a440faa6770bb9a98a3bd/synthpop/draw.py#L72-L75

Can anybody provide insight into the circumstances in which this condition is hit? For reference, I have defined my own recipe of Census fields to pull based on `starter2.Starter`, and am running into this error in some counties but not all.

**Comment by aastha-shah** [comment]
I'm facing this as well, though I'm trying it with some other data. I once fixed it before by removing a few variables that seemed to have numbers that were a bit inaccurate, but I'm stuck now on a different dataset. Do let me know if you figure out what the issue is! @frproulx

**Comment by frproulx** [comment]
Yes, I found that in my case it was due to a typo in one of the field values in my recipe and thus a discrepancy in the way values were getting recoded between my marginal distributions and my joint distribution. I will file an issue suggesting a tool to check for this type of problem.
